### ISSUE TITLE
Keyboard shortcut to open the emoji picker

### ISSUE THREAD

**Issue by ewen-lbh** [Vtrois/gitmoji-vscode#1]
I don't know if this is possible but i'd be definitely useful, as a nice QoL improvement

**Comment by Lesquivemeau** [comment]
have you tried win+. ?

**Comment by seatonjiang** [comment]
You can press `Ctrl + Shift + P ` or `Command ⌘ + Shift ⇧ + P `to choose the Gitmoji tab, and then you can choose the emoji.

**Comment by ewen-lbh** [comment]
Note that I found a simple way to trigger it with a keyboard shortcut, by setting the command `extension.Gitmoji` to a shortcut. I should've look in the extension's "Contributions" tab 😅
