### ISSUE TITLE
✨ Add gitmoji-vscode to the tools in gitmoji's README

### ISSUE THREAD

**Issue by johannchopin** [vtrois/gitmoji-vscode#10]
Hey 👋 

Like your work in this vscode extension 👍  I will recommend you to add it in the [related-tools](https://github.com/carloscuesta/gitmoji#related-tools) section from the gitmoji repo's README.

**Comment by seatonjiang** [comment]
Thank you for your reminder, I submitted a new PR https://github.com/carloscuesta/gitmoji/pull/521
