### ISSUE TITLE
Extension icon is breaking

### ISSUE THREAD

**Issue by bhuvansingla** [vtrois/gitmoji-vscode#11]
The gitmoji extension icon is breaking after the latest VS code update. 

Some other icons also broke after the update, but they got fixed within a day or two. Only the gitmoji icon hasn't fixed yet. It's been over a week now. 

Screenshot:
![image](https://user-images.githubusercontent.com/16359086/88157115-f71ec080-cc27-11ea-9857-527834990f51.png)

**Comment by seatonjiang** [comment]
Hi, @bhuvansingla 

This problem will be fixed in v0.2.1, thanks for feedback.

![image](https://user-images.githubusercontent.com/57834639/88164901-6657dd00-cc47-11ea-88a0-25e2d1e86ca2.png)

**Comment by bhuvansingla** [comment]
It's working fine now. Thank you @seatonjiang!
