### ISSUE TITLE
Selecting an emoji hides the source control panel in the sidebar

### ISSUE THREAD

**Issue by metalelf0** [vtrois/gitmoji-vscode#12]
When I select a gitmoji, the "Source control" panel is hidden and I have to open it again. The emoji gets correctly added to the commit message. Let me know if I can provide any additional useful information. Thanks!

Extension version: v0.2.1
VScode version: 1.48.0-insider

**Comment by seatonjiang** [comment]
Hi @metalelf0 ,
Can you provide a gif to demonstrate this? I'm not testing this at the moment. As you know, I've been doing a lot of offline work in recent months due to COVID-19, such as volunteering at the hospital, so I'm very sorry that I haven't dealt with this issue during this time.

**Comment by metalelf0** [comment]
Hi @seatonjiang , thanks for answering and most of all for volunteering! Be proud of yourself.
I just tested the behaviour with VScode version 1.49.0-insider and extension version v0.2.2 and the issue is not here anymore.

Thanks again and have a great day!
