### ISSUE TITLE
Cursor at the beginning of the commit input after emoji insertion

### ISSUE THREAD

**Issue by bcrespy** [vtrois/gitmoji-vscode#15]
Hello,

Thanks for your work I really like this extension :) 

Since the 2 last updates of VSCODE, after the insertion of the emoji, the cursor is not placed after the emoji as it used to be but ends up being before the emoji. I realize that pressing the right arrow twice is not a big deal, however this extension is all about optimizing our workflow so I figured maybe this issue should be reported.

- Version: 1.51.0
- Electron: 9.3.3
- Chrome: 83.0.4103.122
- Node.js 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Windows_NT x64 10.0.18363

**Comment by seatonjiang** [comment]
Hi, @bcrespy 

I just tested it and it works fine and doesn't reproduce the problem you describe. 

This looks like the same issue as #4, the only difference in our configuration is the Windows version. let's wait a few more days to see if we get the same feedback.

Version: 1.51.0 (user setup)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
**OS: Windows_NT x64 10.0.19041**

**Comment by bcrespy** [comment]
As of today I cannot reproduce the bug anymore. Nothing has changed to my setup, no update or anything.
I'll try to understand the conditions in which the bug occurs if it occurs again.

**Comment by seatonjiang** [comment]
Hi @bcrespy , if you encounter this problem again, please re-open the issue, it is temporarily closed!
