### ISSUE TITLE
Initial Emoji list doesn't render

### ISSUE THREAD

**Issue by mstroiu** [vtrois/gitmoji-vscode#26]
**Description**
Initial Emoji list doesn't render

**To Reproduce in VS Code**
1. Go to Git Source Control
2. Click on on the Emoji icon
3. Search bar is showing but when searching nothing shows
4. Emoji list doesn't render

**Expected behavior**
Should show exactly as the image below:
![image](https://cdn.jsdelivr.net/gh/vtrois/gitmoji-vscode@1/images/about.gif)

**Screenshots**
![image](https://user-images.githubusercontent.com/4835449/123788595-def9fb80-d8e4-11eb-865e-502ea8da40f1.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur (Darwin x64 20.5.0)
 - Version 11.4
 
 **VS Code**
- Version: 1.57.1
- Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
- Date: 2021-06-17T13:28:32.912Z
- Electron: 12.0.7
- Chrome: 89.0.4389.128
- Node.js: 14.16.0
- V8: 8.9.255.25-electron.0

**Comment by seatonjiang** [comment]
Hi, @mstroiu I can't seem to reproduce the problem you describe properly in the same environment, are you clicking on that smiley icon without the option below?

**Comment by mstroiu** [comment]
Please see the GIF below

<img src="https://i.ibb.co/kc2hBtg/Jul-07-2021-8-04-32-PM.gif" alt="Jul-07-2021-8-04-32-PM" border="0">

What option are you referring to?

**Comment by mstroiu** [comment]
I managed to fix the issue but I forgot to write down the exact lines that were in settings.json which was causing this issue.
