### ISSUE TITLE
无法正常显示emoji相关的文案

### ISSUE THREAD

**Issue by YangZhaocool** [vtrois/gitmoji-vscode#27]
为啥我的中、英版的emoji都无法做到预览图那样 
输入emoji之后会出现相关的文案
![zh](https://user-images.githubusercontent.com/31984495/124349905-20134800-dc24-11eb-877c-9c46931c8fae.gif)
![en](https://user-images.githubusercontent.com/31984495/124349908-243f6580-dc24-11eb-8ec9-3fd7d57498bd.gif)
这是预览图
![68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f7674726f69732f6769746d6f6a692d7673636f646540312f696d616765732f61626f75742e676966](https://user-images.githubusercontent.com/31984495/124349994-8a2bed00-dc24-11eb-9d3a-6e9d150d16ae.gif)

**Comment by YangZhaocool** [comment]
这是预览图
![68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f7674726f69732f6769746d6f6a692d7673636f646540312f696d616765732f61626f75742e676966](https://user-images.githubusercontent.com/31984495/124349994-8a2bed00-dc24-11eb-9d3a-6e9d150d16ae.gif)

**Comment by seatonjiang** [comment]
你说的这个 docs: balabala 这种的是手打的，演示图是复制上去的。
