### ISSUE TITLE
Cursor placed before emoji

### ISSUE THREAD

**Issue by will-stone** [vtrois/gitmoji-vscode#4]
Hi,

The latest VSCode update (v1.42.0) places the input cursor before the emoji. If I get a moment, I'll have a look into it, unless you know what the issue is?

Thanks,

Will.

**Comment by will-stone** [comment]
I've done quite a bit of research on this, experimenting with various tactics, but I can only conclude that it is not possible to programmatically move the caret in the SCM message input box and this must be due to a bug with VSCode itself.

**Comment by seatonjiang** [comment]
I looked through the change log, but I don't seem to find the relevant content. Please use the following methods first, write the information first, and then add emoji.

![image](https://user-images.githubusercontent.com/57834639/75605401-8b737400-5b1d-11ea-8c68-1004ec197005.png)

**Comment by will-stone** [comment]
I think VSCode changed the behaviour of this when the input field got upgraded to the Monaco editor. I've gotten used to hitting `cmd-right` after selecting the emoji but I was really hoping this would be temporary.

**Comment by seatonjiang** [comment]
@will-stone 
I don't know what happened, but it seems to have been fixed by VSCODE and I verified the problem using 1.46.1

![image](https://user-images.githubusercontent.com/57834639/86465454-37df9400-bd64-11ea-9914-27510ac8e913.png)
![img](https://oss.payjs.cn/5eff18bb2ac55)

**Comment by will-stone** [comment]
Nice! Alas, I've stopped using gitmoji in my workflow, but I may be back one day 😄
