### ISSUE TITLE
Focus not going back to commit message filed after emoji selection (with keyboard)

### ISSUE THREAD

**Issue by dnlek** [vtrois/gitmoji-vscode#8]
When I reveal emojis panel and select emoji using keyboard - i lose focus on commit message.
It works fine if i select icon using mouse though.

vscode: 1.46.1
extension: 0.1.9

Other than that cool extension - thanks :)

**Comment by seatonjiang** [comment]
Thanks for your feedback, I reproduced this problem and am trying to fix it.

**Comment by seatonjiang** [comment]
Hi @dnlek ,This issue has been fixed, please update to a new version and try it out!

**Comment by seatonjiang** [comment]
No feedback has been received for a long time, so this issues will be closed temporarily, if there are still problems, please feedback again.
