### ISSUE TITLE
Feature Request: Filter emojis by name

### ISSUE THREAD

**Issue by dnlek** [vtrois/gitmoji-vscode#9]
Before using extension i typed all the emoji names by hand `:ambulance:` etc... 
It would be cool to be able to find gitmoji on the list by typing `ambulance`

**Comment by seatonjiang** [comment]
![image](https://user-images.githubusercontent.com/57834639/91656020-d92a6280-eae7-11ea-9ffc-c55b3ef18bdd.png)

Hi @dnlek 
Are you referring to the shortcode for entering emoji here, e.g. ambulance? 
As you know, I've been doing a lot of offline work in recent months due to COVID-19, such as volunteering at the hospital, so I'm very sorry that I haven't dealt with this issue during this time.

**Comment by dnlek** [comment]
Hey @seatonjiang  - no worries - plugin is super cool and work at hospital is much more improtant than this feature :) 

About the feature - correct. ATM if i type `ambulance` in that field - it won't show me anything. 
Would be cool if i could type `fire`, `ambulance` or other emoji name to filter them. Sometimes i am having hard time to find it by provided description. 
So in attached screenshot - it would show me 
🚑  Critical hotfix

![image](https://user-images.githubusercontent.com/547490/91822437-1867c900-ec38-11ea-8667-370ca2e6e0e2.png)

**Comment by seatonjiang** [comment]
Hi @dnlek , this issue has been added in version 1.0.2 and we thank @xeloader for contributing the PR.

![image](https://user-images.githubusercontent.com/57834639/100165728-e40c4d80-2eb2-11eb-98a0-1f221e2c9de8.png)

**Comment by dnlek** [comment]
Great :) Thanks @seatonjiang @xeloader  Waiting for update in vscode :)

**Comment by seatonjiang** [comment]
@dnlek The version has been updated, please update in VSCode

**Comment by dnlek** [comment]
Hey - I wanted to check it out but i must be doing something wrong. 
I checked for updated in vscode but i see none.
I have vscode 1.51.1 and gitmoji plugin in version 1.0.3
but when i open up gitmoji list and type ambulance - nothing shows up.
![image](https://user-images.githubusercontent.com/547490/100972329-e7e64280-3538-11eb-9ab1-563509b60985.png)

**Comment by seatonjiang** [comment]
@dnlek This feature is disabled by default and needs to be configured to be turned on.

![image](https://user-images.githubusercontent.com/57834639/100973321-50531500-3575-11eb-97b4-133019826ed9.png)

![image](https://user-images.githubusercontent.com/57834639/100973403-7678b500-3575-11eb-8789-b96d5f409b3a.png)

![image](https://user-images.githubusercontent.com/57834639/100973435-7f698680-3575-11eb-837f-f17742b0f761.png)

**Comment by dnlek** [comment]
oh right - thanks @seatonjiang now it's working like a charm! :) Thank you very much!
